### ISSUE TITLE
[Admin Space] - Centralization of all its actions

### ISSUE THREAD

**Issue by popolito1** [AbdullatifGhajar/advanced-programming-2023#41]
- Frontend : 
  - [x] Create 4 buttons that corresponds to this : 
<img width="584" alt="Capture d’écran 2024-01-25 à 11 33 44" src="https://github.com/AbdullatifGhajar/advanced-programming-2023/assets/60854956/421cf640-93bd-41a4-8938-ff9af42fb22c">

  - [x] Add new internship space #37 
  - [ ] Manage an internship space #38
  - [ ] Delete an internship  #39
  -  [ ] Validation of interships #40 
- Backend : 
  - [ ] Frontend is shown only for admin user
